services:
    dos.form.type.user_search:
        class: DoS\UserBundle\Form\Type\UserSearchType
        arguments:
            - @dos.repository.user
            - @router
            - "route_api_user_search"
        tags:
            - {name: form.type, alias: dos_user_search}

    dos.form.type.user_reistration:
        class: DoS\UserBundle\Form\Type\RegistrationType
        arguments:
            - %dos.model.user.class%
            - %dos.validation_group.registration%
            - @dos.repository.customer
            - @dos.form.listener.user_confirmation
        tags:
            - {name: form.type, alias: dos_registration}

    dos.form.type.user_avatar:
        class: DoS\UserBundle\Form\Type\UserAvatar
        arguments:
            - %dos.model.user.class%
            - %dos.validation_group.user_avatar%
        tags:
            - {name: form.type, alias: dos_user_avatar}

    dos.form.type.customer_profile:
        class: DoS\UserBundle\Form\Type\CustomerProfileType
        arguments:
            - %dos.model.user.class%
            - %sylius.validation_group.profile%
        tags:
            - {name: form.type, alias: dos_customer_profile}

    dos.form.listener.user_confirmation:
        class: DoS\UserBundle\Form\EventListener\ConfirmationFormListener
        arguments:
            - @dos.user.confirmation.factory
            - @request_stack
