parameters:
    dos.listener.user_acl.class: DoS\UserBundle\EventListener\UserAclListener
    dos.listener.user_aware.class: DoS\UserBundle\EventListener\UserAwareResourceListener
    dos.listener.user_confirmation.class: DoS\UserBundle\EventListener\UserConfirmationListener
    dos.listener.default_username.class: DoS\UserBundle\EventListener\DefaultUsernameListener
    dos.listener.user_security_role.class: DoS\UserBundle\EventListener\UserSecurityRoleListener

services:
    dos.listener.user_acl:
        class: %dos.listener.user_acl.class%
        arguments:
            - @service_container
        tags:
            - {name: doctrine.event_listener, event: postPersist, priority: -128}

    dos.listener.user_aware:
        class: %dos.listener.user_aware.class%
        arguments:
            - @dos.user.security
        tags:
            - {name: doctrine.event_subscriber, connection: default}

    dos.listener.user_confirmation:
        class: %dos.listener.user_confirmation.class%
        arguments:
            - @dos.user.confirmation.factory
        tags:
            - {name: kernel.event_listener, event: sylius.customer.post_register, method: sendConfirmation, priority: 128}

    dos.listener.user_security_role:
        class: %dos.listener.user_security_role.class%
        tags:
            - {name: kernel.event_listener, event: sylius.customer.pre_update, method: resizeUserRoles}
