parameters:
    dos.listener.user_acl.class: DoS\UserBundle\EventListener\UserAclListener
    dos.listener.user_aware.class: DoS\UserBundle\EventListener\UserAwareResourceListener

services:
    dos.listener.user_acl:
        class: %dos.listener.user_acl.class%
        arguments:
            - @service_container
        tags:
            - {name: doctrine.event_listener, event: postPersist, piority: -128}

    dos.listener.user_aware:
        class: %dos.listener.user_aware.class%
        arguments:
            - @dos.user.security
        tags:
            - {name: doctrine.event_subscriber, connection: default}
