parameters:
    dos.user.twig.user_profile.class: DoS\UserBundle\Twig\UserProfile

services:
    dos.user.twig.user_profile:
        class: %dos.user.twig.user_profile.class%
        arguments:
            - @liip_imagine.cache.manager
        tags:
            - {name: twig.extension}
