DoS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            message: ui.trans.user.username.unique
            fields: [username]
            groups: [Default, registration]

    properties:
        file:
            - Image:
                #mimeTypesMessage: ui.trans.user.avatar.invalid_mime_type
                maxSize: 10M
                #maxSizeMessage: ui.trans.user.avatar.invalid_max_size
                groups: [Profile]

DoS\UserBundle\Model\Customer:
    constraints:
        - Sylius\Bundle\UserBundle\Validator\Constraints\RegisteredUser:
            message: ui.trans.profile.registered
            groups: [registration]

    properties:
        mobile:
            - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber:
                defaultRegion: TH
                message: ui.trans.customer.mobile.invalid
                groups: [Default, registration]

DoS\UserBundle\Model\OneTimePassword:
    properties:
        token:
            - NotBlank:
                message: ui.trans.user.otp.token.blank
                groups: [Default]

        verify:
            - NotBlank:
                message: ui.trans.user.otp.verify.blank
                groups: [Default]
