DoS\UserBundle\Model\User:
    properties:

        file:
            - Image:
                #mimeTypesMessage: ui.trans.user.avatar.invalid_mime_type
                maxSize: 10M
                #maxSizeMessage: ui.trans.user.avatar.invalid_max_size
                groups: [Profile]

        mobile:
            - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber:
                defaultRegion: TH
                message: ui.trans.profile.mobile.invalid
                groups: [Profile]

DoS\UserBundle\Model\OneTimePassword:
    properties:
        token:
            - NotBlank:
                message: ui.trans.user.otp.token.blank
                groups: [Default]

        verify:
            - NotBlank:
                message: ui.trans.user.otp.verify.blank
                groups: [Default]
