DoS\UserBundle\Model\OneTimePassword:
    type: mappedSuperclass
    table: sylius_user_otp

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        token:
            type: string

        verify:
            type: string

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create

        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    manyToOne:
        subject:
            targetEntity: DoS\UserBundle\Model\UserInterface
            cascade: [all]
