DoS\UserBundle\Model\User:
    type: mappedSuperclass
    table: dos_user

    fields:
        locale:
            type: string
            length: 5
            nullable: true

        displayname:
            type: string
            nullable: true
            column: displayname

        path:
            type: string
            nullable: true
            column: path

        confirmationType:
            type: string
            column: confirmation_type
            nullable: true

        confirmedAt:
            type: datetime
            nullable: true
            column: confirmed_at
