DoS\UserBundle\Model\User:
    type: mappedSuperclass
    table: sylius_user

    fields:
        locale:
            type: string
            length: 5
            nullable: true

        displayname:
            type: string
            nullable: true
            column: displayname

        confirmationType:
            type: string
            column: confirmation_type
            nullable: true

        confirmedAt:
            type: datetime
            nullable: true
            column: confirmed_at

    manyToMany:
        authorizationRoles:
            targetEntity: Sylius\Component\Rbac\Model\RoleInterface
            joinTable:
                name: sylius_user_roles
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE

    manyToOne:
        picture:
            targetEntity: Sylius\Component\Media\Model\ImageInterface
            cascade: [all]
            joinColumn:
                nullable: true
                onDelete: "CASCADE"
                image_id:
                    referencedColumnName: id
