DoS\UserBundle\Model\User:
    type: mappedSuperclass
    table: dos_user

    fields:
        locale:
            type: string
            length: 5
            nullable: true

        displayname:
            type: string
            nullable: true
            column: displayname

        mobile:
            type: phone_number
            nullable: true
            column: mobile

        path:
            type: string
            nullable: true
            column: path
