DoS\UserBundle\Model\UserOAuth:
    type: mappedSuperclass
    table: dos_user_oauth

    fields:

        profilePicture:
            type: string
            nullable: true
            column: profile_picture
