route_backend_permission_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.permission:indexAction
        _sylius:
            template: ui:package/backend/Permission:index.html.twig
            paginate: false
            sorting:
                left: asc

route_backend_permission_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.permission:createAction
        _sylius:
            template: ui:package/backend/Permission:create.html.twig
            redirect: route_backend_permission_index

route_backend_permission_update:
    path: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.permission:updateAction
        _sylius:
            template: ui:package/backend/Permission:update.html.twig
            redirect: route_backend_permission_index

route_backend_permission_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.permission:deleteAction
        _sylius:
            redirect: route_backend_permission_index
