route_backend_role_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.role:indexAction
        _sylius:
            template: ui:backend/Role:index.html.twig
            paginate: false
            sorting:
                left: asc

route_backend_role_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.role:createAction
        _sylius:
            template: ui:backend/Role:create.html.twig
            redirect: route_backend_role_index

route_backend_role_update:
    path: /{id}/edit
    methods: [GET, PUT, PATCH]
    defaults:
        _controller: sylius.controller.role:updateAction
        _sylius:
            template: ui:backend/Role:update.html.twig
            redirect: route_backend_role_index

route_backend_role_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.role:deleteAction
        _sylius:
            redirect: route_backend_role_index
