route_backend_setting_security:
    path: /security
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: security
        template: ui:package/backend/Settings:security.html.twig
        _sylius:
            redirect: route_backend_setting_general
