DoS\UserBundle\Model\Customer:
    constraints:
        - DoS\UserBundle\Validator\Constraints\RegisteredUser:
            message: ui.trans.profile.registered
            emailMessage: ui.trans.profile.email_registered
            mobileMessage: ui.trans.profile.mobile_registered
            groups: [dos, dos_registration]

    properties:
        mobile:
            - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber:
                defaultRegion: TH
                message: ui.trans.customer.mobile.invalid
                groups: [dos]
