DoS\UserBundle\Model\OneTimePassword:
    properties:
        token:
            - NotBlank:
                message: ui.trans.user.otp.token.blank
                groups: [dos]

        verify:
            - NotBlank:
                message: ui.trans.user.otp.verify.blank
                groups: [dos]
