DoS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            message: ui.trans.user.username.unique
            fields: [username]
            groups: [dos, dos_registration]
