DoS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            message: ui.trans.user.username.unique
            fields: [username]
            groups: [dos, dos_registration]

    properties:
        file:
            - Image:
                #mimeTypesMessage: ui.trans.user.avatar.invalid_mime_type
                maxSize: 10M
                #maxSizeMessage: ui.trans.user.avatar.invalid_max_size
                groups: [dos]
