route_user_request_password_reset_token:
    path: /request-token
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:requestPasswordResetTokenAction
        _sylius:
            form: sylius_user_request_password_reset
            template: ui:security:requestPasswordReset.html.twig
            redirect: route_user_security_login

route_user_request_password_reset_pin:
    path: /request-pin
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:requestPasswordResetPinAction
        _sylius:
            form: sylius_user_request_password_reset
            template: ui:security:requestPasswordReset.html.twig
            redirect: route_user_security_login

route_user_password_reset:
    path: /{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:resetPasswordAction
        _sylius:
            form: sylius_user_reset_password
            template: ui:security:resetPassword.html.twig
            redirect: route_user_security_login
            redirect_expired_token:
                pin: route_user_request_password_reset_pin
                token: route_user_request_password_reset_token
