route_backend_security_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: ui.controller.backend.security:loginAction

route_backend_security_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: ui.controller.backend.security:checkAction
