route_user_security_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.user_security:loginAction
        _sylius:
            form: sylius_user_security_login
            template: ui:security:login.html.twig

route_user_security_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: sylius.controller.user_security:checkAction

route_user_security_logout:
    path: /logout
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user_security:logoutAction

# provent not found route
sylius_route_security:
    resource: "@SyliusUserBundle/Resources/config/routing/security.yml"
