route_user_security_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security:loginAction
        _sylius:
            form: sylius_user_security_login
            template: ui:security:login.html.twig

route_user_security_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: sylius.controller.security:checkAction

route_user_security_logout:
    path: /logout
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.security:logoutAction
